# Generated by Django 2.1.7 on 2019-02-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('subsc_userid', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='readed',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AddField(
            model_name='post',
            name='userid',
            field=models.IntegerField(default=1),
        ),
    ]
