# Generated by Django 2.0.13 on 2019-02-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_auto_20190215_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150)),
                ('slug', models.CharField(blank=True, max_length=150, unique=True)),
                ('userid', models.IntegerField(default=1)),
                ('introtext', models.TextField(blank=True, db_index=True)),
                ('fulltext', models.TextField(blank=True, db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('readed', models.TextField(blank=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('subsc_userid', models.IntegerField(default=1)),
            ],
        ),
    ]
