# Generated by Django 2.0.13 on 2019-02-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190215_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='readed',
        ),
    ]
