# Generated by Django 2.0.13 on 2019-02-15 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postuser',
            name='subsc_userid',
        ),
        migrations.RemoveField(
            model_name='postuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='postuser',
            name='subs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
